development:
  adapter: postgresql
  encoding: unicode
  #host: tanf-devdb.state.ar.us
  #database: waaps_development
  #username: waps_app
  #password: app_waps
  host: localhost
  username: thirumalgonguntala
  password: 
  database: caddy_cloud
  pool: 5

