development:
  adapter: postgresql
  encoding: unicode
  #host: tanf-devdb.state.ar.us
  #database: waaps_development
  #username: waps_app
  #password: app_waps
  host: localhost
  port: 5432
  username: postgres
  password: 
  database: caddy_cloud_development
